python_django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import(handler400,handler403,handler404,handler500)

handler500 = 'polls.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

python_django/polls/urls.py
from django.urls import path
from . import views

from .views import *

app_name = 'polls'



urlpatterns = [
    path('', views.index, name='index'), # /polls/
    path('<int:question_id>/', views.detail, name='detail'), # /polls/5/
    path('<int:question_id>/results/', views.results, name='results'), # /polls/5/results/
    path('<int:question_id>/vote/', views.vote, name='vote'), # /polls/5/vote/
    path('create/', views.create, name='create'), # /polls/create/
    path('<int:question_id>/modify/', views.modify, name='modify'), # /polls/5/modify
    path('<int:question_id>/delete/', views.delete, name='delete') # /polls/5/delete

]

python_django/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

python_django/polls/views.py
from genericpath import exists
from secrets import choice
from time import time
from django.template import RequestContext
from django.views import generic
from django.db.models import Q
from xmlrpc.client import DateTime
from wsgiref.simple_server import sys_version
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime,date,timedelta
from django.core.paginator import Paginator
from .models import Question, Choice
from .checkMethod import *
from .errorMessage import *
from django.utils.functional import cached_property

def index(request):
    search = request.GET.get("search", "")
    searchDateFrom = request.GET.get("searchDateFrom","")
    searchDateTo = request.GET.get("searchDateTo","")
    From = validate_date_form_check_from(searchDateFrom)
    To = validate_date_form_check_to(searchDateTo)
    date_today = datetime.now() + timedelta(days=1)
    date_today_from = datetime.now() - timedelta(days=1)
    pages = 0
   
    # 検索条件(質問、日付)
    if search != '':
        all_questions = Question.objects.filter(question_text__contains=search)
    elif searchDateTo != '' and searchDateFrom != '':
        all_questions = Question.objects.filter(pub_date__range=[From, To ])
    elif searchDateFrom != '':
        if len(searchDateFrom) == 10 or From == str:
            searchDateFrom = str(searchDateFrom)
        all_questions = Question.objects.filter(pub_date__range=[From, date.today()+timedelta(days=1) ])
    elif searchDateTo != '':
        all_questions = Question.objects.filter(pub_date__range=[date.today() - timedelta(days=10000), To ])
    elif search == "":
        all_questions = Question.objects.all().order_by('-pub_date')  
    if search != '' and searchDateTo != '' and searchDateFrom != '':
        all_questions = Question.objects.filter(question_text__contains=search, pub_date__range=[From, To ])
    elif search != '' and searchDateFrom != '':
        all_questions = Question.objects.filter(question_text__contains=search, pub_date__range=[From, date.today()])
    elif search != '' and searchDateTo != '':
        all_questions = Question.objects.filter(question_text__contains=search, pub_date__range=[date.today() - timedelta(days=10000), To])
    if len(searchDateTo) == 10 and searchDateTo == str:            
        all_questions = Question.objects.all().order_by('pub_date')
    else:
        pass
    if len(search) > 10:
        all_questions = Question.objects.all().order_by('pub_date')
    else:
        pass

    page = int(request.GET.get('page', 1)) # URLからpageの値を取得するときに使用、page値なしで呼び出された場合にはデフォルトで 1 という値を設定する
    paginator = Paginator(all_questions, 7) # all_questions:質問全体、7:ページごとに表示する質問の数
    questions = paginator.get_page(page) # 要求されたページに対応するページングオブジェクトを生成
    for question in questions:
        question.pub_date = question.pub_date.strftime("%Y-%m-%d")
    # これにより、Django内部では、データ全体を照会するのではなく、そのページのデータのみを照会するようにクエリが変更される
    
    # 前のページに戻る
    for i in questions.paginator.page_range:
        if i == questions.number:
            pages = i
            request.session['pages'] = i

    request.session['search'] = request.GET.get("search", "")
    request.session['searchDateFrom'] = request.GET.get("searchDateFrom","")
    request.session['searchDateTo'] = request.GET.get("searchDateTo","")

    context = {
        'questions':questions,
        'search':search,
        'searchDateFrom':searchDateFrom,
        'searchDateTo':searchDateTo,
        'To':To,
        'From':From,
        'error_massage':"正しい日付範囲をセットしてください。",
        'error_massage2':"日付Toは最大本日の日付にセットしてください。",
        'error_massage3':"日付Fromは本日より大きな日付は入力出来ません。",
        'error_massage4':"日付FromとToは本日より大きな日付は入力出来ません。",        
        'error_massage5':"正しい日付フォーマットで入力してください。",
        'error_massage6':"質問がありません。",        
        'date_today': date_today,
        'date_today_from': date_today_from,
        'pages':pages,
        'search':request.session['search'],
        'searchDateFrom':request.session['searchDateFrom'],
        'searchDateTo':request.session['searchDateTo'],
    }

    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    all_choice = question.choice_set.all()
    all_choice_votes = []
    view_select = {}

    for i in all_choice:
        all_choice_votes.append(i.votes)
    if all_choice_votes.count(0) != len(all_choice_votes):
        view_select['nomodify'] = 0

    return render(request, 'polls/detail.html', {'question':question, 'view_select':view_select, 'pages':request.session['pages'],'search':request.session['search'],
        'searchDateFrom':request.session['searchDateFrom'],'searchDateTo':request.session['searchDateTo'], })

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    all_choice = question.choice_set.all()
    all_choice_votes = []
    view_select = {}
    for i in all_choice:
        all_choice_votes.append(i.votes)

    if all_choice_votes.count(0) != len(all_choice_votes):
        view_select['nomodify'] = 0

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])

    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "選択肢を選んでください。",
            'view_select': view_select,
            'pages':request.session['pages'],
            'search':request.session['search'],
            'searchDateFrom':request.session['searchDateFrom'],
            'searchDateTo':request.session['searchDateTo'],
        })

    else:
        selected_choice.votes +=1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def create(request):
    if request.method == 'POST':
        # 入力された質問と選択肢を取得する
        select_all = {}
        for select in request.POST:
            value = request.POST.get(select, None)
            select_all["{}".format(select)] = value
        question = select_all.pop('question')
        select_all.pop('csrfmiddlewaretoken')
        
        # errorメッセージ
        error_messages = [] 
        
        # 質問必須チェック
        if not required_check(question):
            error_messages.append(error_message.question_required())
        
        # 質問スペースのみチェック
        if only_space_check(question):
            error_messages.append(error_message.only_space())

        # 質問桁数チェック
        if length_check(question):
            error_messages.append(error_message.length("質問"))
        
        # 質問重複チェック
        if question_double_check(question):
            error_messages.append(error_message.question_double())
        
        # 選択肢数（必須）チェック
        if not select_count_check(select_all.values()): 
            error_messages.append(error_message.select_count())

        # 選択肢重複チェック
        if select_double_check(select_all.values()):
            error_messages.append(error_message.select_double())
        
        # 選択肢桁数チェック
        if select_length_check(select_all.values()):
            error_messages.append(error_message.length("選択肢"))

        if not len(error_messages):
            pub_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            question = Question.objects.create(question_text=question.strip(), pub_date=pub_date)
            for select in select_all.values():
                if not only_space_check(select) and required_check(select):
                    Choice.objects.create(choice_text=select.strip(), question_id=question.id)
            return redirect('/polls')
        return render(request, 'polls/create.html', {'error_messages':error_messages, 'select_all':select_all, 'question':question})
    else:
        return render(request, 'polls/create.html')

def delete(request, question_id):
    if request.method == "GET":
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/delete.html', {'question':question, 'pages':request.session['pages'], 'search':request.session['search'],
            'searchDateFrom':request.session['searchDateFrom'],
            'searchDateTo':request.session['searchDateTo'],})

    elif request.method == "POST":
        question = get_object_or_404(Question, pk=question_id)
        question.delete()
        return redirect('/polls/')

def modify(request, question_id):
    if request.method == 'POST':
        # 入力された質問と選択肢を取得する
        old_question = Question.objects.get(pk=question_id)
        old_choice = old_question.choice_set.all()
        select_all = {}
        for select in request.POST:
            value = request.POST.get(select, None)
            select_all["{}".format(select)] = value
        new_question = select_all.pop('question')
        select_all.pop('csrfmiddlewaretoken')

        # errorメッセージ
        error_messages = [] 
        # 質問必須チェック
        if not required_check(new_question):
            error_messages.append(error_message.question_required())
        # 質問スペースのみチェック
        if only_space_check(new_question):
            error_messages.append(error_message.only_space())
        # 質問桁数チェック
        if length_check(new_question):
            error_messages.append(error_message.length("質問"))
        # 選択肢数（必須）チェック
        if not select_count_check(select_all.values()): 
            error_messages.append(error_message.select_count())
        # 選択肢重複チェック
        if select_double_check(select_all.values()):
            error_messages.append(error_message.select_double())
        # 選択肢桁数チェック
        if select_length_check(select_all.values()):
            error_messages.append(error_message.length("選択肢"))
        # MODIFY質問重複チェック 

python_django/polls/templates/polls/base.html
{% load mathfilters %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <!-- jQuery library (served from Google) -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <!-- jcSlider Javascript file -->
        <script src="jquery.maxcharwarning.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
        <script type="text/javascript" src="{% static 'polls/style.js' %}"></script>
        <script type="text/javascript" src="{% static 'polls/style2.js' %}"></script>
        <script type="text/javascript">

            function checkForm($this)
            {
            $(document).on("change", 'input', function(){
            let str = $(this).val()
            str = str.replace(/[Ａ-Ｚａ-ｚ０-９]/g, function(s) {
            return String.fromCharCode(s.charCodeAt(0) - 0xFEE0);
            });

            $(this).val(str);
            });
            }

        </script>

        <style>
            .outer {
                text-align: center;
            }
            .inner {
                display: inline-block;
            }
            td {
                vertical-align : middle;
                text-align: left;
            }   
            .button {
                display: inline-block;
                border-style: solid;
                color: black;
                background-color: rgb(225, 224, 224);
                border-width:1px;
                border-color: darkgray;
                text-decoration: none;
            }
            .input-error{
                box-shadow: 0 0 5px red;
                border: 1px solid red;
            }
            .name{
                font-size:15px;
                color:red;
                font-weight: bold;
            }
            .name2{
                font-size:15px;
                color:red;
                font-weight: bold;
            }
        </style>
    </head>

    <body>  
        <div class="container">
        {% block content %}
        {% endblock %}
        </div>
    </body>
</html>

python_django/polls/templates/polls/create.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="outer">
    <div>
        <h1>新規作成</h1>
    </div>

    <form method="post" action="." >
        {% csrf_token %}
        <div>
            <strong><label for="question" style="font-size: large;">質問</label></strong><br><br>
            <input type="text" name="question" value="{{ question }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="質問は20文字以内でおねがいします。"data-max-length="20" data-max-length-warning-container="name" onInput="checkForm(this)">
        </div>
        <span class="name"></span>
        <br>
        <div>
            <strong><label for="select_list" style="font-size: large;">選択肢</label></strong><br><br>
            <input type="text" name="select1" value="{{ select_all.select1 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="選択肢は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
            <input type="text" name="select2" value="{{ select_all.select2 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="選択肢は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
            <input type="text" name="select3" value="{{ select_all.select3 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="選択肢は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
            <input type="text" name="select4" value="{{ select_all.select4 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="選択肢は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
        </div>
    
        <span class="name2"></span>
        <br>
        {% for error in error_messages %}
        <div style="color: red;">
            <strong>{{error}}</strong><br>
        </div>
        {% endfor %}
    
        <div>
            <button type="submit" >登録</button>
            <button type="button" onclick="location.href='/polls'">一覧画面に戻る</button>
        </div>
    </form>
</div>
{% endblock %}

python_django/polls/templates/polls/delete.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="outer">
    <form method="POST">
    {% csrf_token %}
        <h2>{{ question.question_text }}</h2>
        <p>この質問を削除しますか？</p>
        <a href="javascript:history.back();"><button>はい</button></a>
        <button type="button" onclick="location.href='/polls/?page={{pages}}&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}'">前の画面に戻る</button>
    </form>
</div>
{% endblock %}

python_django/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="outer">
    <div>
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
        

        <div class="inner">
            <table>
                {% for choice in question.choice_set.all %}
                <tr>
                    <td><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"></td>
                    <td><label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label></td> 
                    <td>--</td>
                    <td>{{ choice.votes }}票</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        {% if error_message %}
            <p style="color: red;"><strong>{{ error_message }}</strong></p>
        {% endif %}

        {% if view_select %}
        <div>
            <button type="submit">投票</button>
            <button type="button" onclick="location.href='/polls/?page={{pages}}&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}'">前の画面に戻る</button> 
            <!-- <a href="javascript:history.back();">前の画面に戻る</a> -->
        </div>
        {% else %}
        <div>
            <button type="submit">投票</button>
            <button type="button" onclick="location.href='/polls/?page={{pages}}&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}'">前の画面に戻る</button>
            <br><br>
            <a href="{% url 'polls:modify' question.id %}" class="button">編集</a>
        {% endif %}
        </div>
        </form>
    </div>
</div>
{% endblock %}

python_django/polls/templates/polls/index.html
{% load mathfilters %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!-- jQuery library (served from Google) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <!-- jcSlider Javascript file -->
    <script src="jquery.maxcharwarning.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
        <script type="text/javascript" src="{% static 'polls/style.js' %}"></script>
        <script type="text/javascript" src="{% static 'polls/style2.js' %}"></script>
    
    <script type="text/javascript">
    function checkForm($this)
            {
            $(document).on("change", 'input', function(){
	        let str = $(this).val()
	        str = str.replace(/[Ａ-Ｚａ-ｚ０-９]/g, function(s) {
	        return String.fromCharCode(s.charCodeAt(0) - 0xFEE0);
	        });

	        $(this).val(str);
            });
            }
    </script>
</head>

<body>
<div class="outer">
        <div class="inner">
            <h2>投票一覧</h2>
        <div>
            <form>
            <div style="display:inline-flex;">質問 : <input style="width: 200px" type="text" placeholder="10文字以内で入力してください" name="search" value="{{ search }}" class ="js-max-char-warning2" data-max-length-warning="質問は10文字以内でおねがいします。" data-max-length="10" data-max-length-warning-container="name" onInput="checkForm(this)"></div>
            <br>
            <span class="name"></span>
            <br>
            <div style="display:inline-flex;">日付 : <input type="text" name="searchDateFrom" value="{{ searchDateFrom }}" onInput="checkForm(this)"><div> ～ </div><input type="text" name="searchDateTo" value="{{ searchDateTo }}" onInput="checkForm(this)"></div>
            <br>
            {% for error in error_messages %}
            <div style="color: red; margin-top: 10px;">
                <strong>{{ error_message2 }}</strong><br>
            </div>
            {% endfor %}
            <p>例：(2022/05/12、2022-05-02、20220502) 空白無しで</p>
            <div>
                <button type="button" onclick="location.href='/polls'">リセット</button>
                <button type="submit">検索</button>  
            </div>
            </form>
        </div>
        <br>
        <div>
            {% if search|length > 10 %}
            <div style="color: red;">
                <strong>10以内に入力してください。</strong><br>
            </div>
            {% endif %}
            <br>
            {% if questions %}
                {% if From > To %}
                    {{ error_massage }}

                {% elif To > date_today and From > date_today %}
                {{ error_massage4 }}

                 {% elif To > date_today %}
                {{ error_massage2 }}

                {% elif From > date_today_from %}
                {{error_massage3 }}


            {% else %}
                    <table border="1">
                        <tr>
                            <th>No</th>
                            <th>pub_date</th>
                            <th style="width: 250px;">questions</th>
                            <th>delete</th>
                        </tr>
                    {% for question in questions %}
                    <tr>
                        <td style="text-align: center;">{{ questions.start_index|add:forloop.counter0 }}</td>
                        <td style="text-align: center;">{{ question.pub_date }}</td>
                        <td><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></td>
                        <td style="text-align: center;"><a href="{% url 'polls:delete' question.id %}"><button>削除</button></a></td>
                    </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% elif questions != '' %}
                {% if search|length > 10 %}
                10以内に入力してください。
                {% endif %}

                {% if From > To %}
                {{ error_massage }} 
                {% elif To > date_today and From > date_today_from %}
                {{ error_massage4 }}
                {% elif To > date_today %}
                {{ error_massage2 }}
                {% elif From > date_today_from %}
                {{error_massage3 }}

                {% elif search != '' and From != '' and To != '' %}
                {{ error_massage6 }}
                {% elif search == '' and From != '' and To != '' %}
                {{ error_massage5 }}
                {% elif search != '' and To != '' %}
                {{ error_massage5 }}
                {% elif search != '' or From == '' or To == '' %}
                {{ error_massage5 }}
                {% elif search != '' or From != ''%}
                {{ error_massage5 }}
                {% elif search != '' or To != '' %}
                {{ error_massage5 }}
                {% elif search != '' %}
                {{ error_massage5 }}
                {% endif %}

            {% endif %}
        </div>

        <br>
    <div>
        <nav>
        <!-- 前のページがある場合　-->
        {% if questions.has_previous %}
            <a href="?page=1&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}"><button>&laquo;</button></a>
            <a href="?page={{ questions.previous_page_number }}&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}"><button>&lsaquo;</button></a>
        <!-- 前のページがない場合 -->
        {% else %}
            <button disabled>&laquo;</button>
            <button disabled>&lsaquo;</button>
        {% endif %}

        <!-- questions.paginator.page_range : range(1, 5) -->
        {% for i in questions.paginator.page_range %}
            <!-- 表示するページボタンの数を指定 -->
            {% if i >= questions.number|sub:1|intdiv:3|mul:3|add:1 and i <= questions.number|sub:1|intdiv:3|add:1|mul:3 %}
                <!-- iと現在のページ番号が同じの場合色を入れる -->
                {% if i == questions.number %}
                    <a href="?page={{i}}&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}"><button style="background-color: rgb(255, 251, 210);">{{i}}</button></a>
                {% else %}
                    <a href="?page={{i}}&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}"><button>{{i}}</button></a>
                {% endif %}
            {% endif %}
        {% endfor %}
        
        <!-- 次のページがある場合 -->
        {% if questions.has_next %}
            <a href="?page={{ questions.next_page_number }}&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}"><button>&rsaquo;</button></a>
            <a href="?page={{ questions.paginator.num_pages }}&search={{ search }}&searchDateFrom={{searchDateFrom}}&searchDateTo={{searchDateTo}}"><button>&raquo;</button></a>
        <!-- 次のページがない場合 -->
        {% else %}
            <button disabled>&rsaquo;</button>
            <button disabled>&raquo;</button>
        {% endif %}
        <br><br>
        <button type="button" onclick="location.href='/polls/create'">新規登録</button>
        </nav>
    </div>
    </div>
</div>
</body>
</html>

python_django/polls/templates/polls/modify.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="outer">
    <form method="post" action=".">
        {% csrf_token %}
        {% if view_select %}
            <div>
                <strong><label for="question" style="font-size: large;">質問</label></strong><br><br>
                <input type="text" name="question" value="{{ question.question_text }}" class ="js-max-char-warning" placeholder="20文字以内に入力" data-max-length-warning="質問は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name" onInput="checkForm(this)">
            </div>
            
            <span class="name"></span>

            <br>
            <div>
                <strong><label for="select_list" style="font-size: large;">選択肢</label></strong><br><br>
                {% for choice in question.choice_set.all %}
                    <input type="text" name="select{{ forloop.counter }}" value="{{ choice.choice_text }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="選択肢は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
                {% endfor %}
                {% if question.choice_set.count == 2 %}
                    <input type="text" name="select3" value="{{ select_all.select3 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="選択肢は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" ><br>
                    <input type="text" name="select4" value="{{ select_all.select4 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="選択肢は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" ><br>
                {% elif question.choice_set.count == 3 %}
                    <input type="text" name="select4" value="{{ select_all.select4 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="選択肢は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" ><br>
                {% endif %}
            </div>

            <span class="name2"></span>

            <div>
                {% if no_modify %}
                <button type="button" onclick="location.href='/polls/{{ question.id }}'">詳細に戻る</button>
                {% else %}
                <button type="submit">更新する</button>
                <button type="button" onclick="location.href='/polls/{{ question.id }}'">詳細に戻る</button>
                {% endif %}
            </div>
        {% else %}
            <div>
                <strong><label for="question" style="font-size: large;">質問</label></strong><br><br>
                <input type="text" name="question" value="{{ new_question }}" class ="js-max-char-warning" placeholder="20文字以内に入力" data-max-length-warning="質問は20文字以内でおねがいします。"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)">
                <span class="name"></span>
            </div><br>

            <div>
                <strong><label for="select_list" style="font-size: large;">選択肢</label></strong><br><br>
                <input type="text" name="select1" value="{{ select_all.select1 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="20文字以内でおねがいします"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
                <input type="text" name="select2" value="{{ select_all.select2 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="20文字以内でおねがいします"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
                <input type="text" name="select3" value="{{ select_all.select3 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="20文字以内でおねがいします"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
                <input type="text" name="select4" value="{{ select_all.select4 }}" class ="js-max-char-warning2" placeholder="20文字以内に入力" data-max-length-warning="20文字以内でおねがいします"  data-max-length="20" data-max-length-warning-container="name2" onInput="checkForm(this)"><br>
            </div>

            <span class="name2"></span>

            {% for error in error_messages %}
            <div style="color: red;">
                <strong>{{error}}</strong><br>
            </div>
            {% endfor %}

            <div>
                <button type="submit">更新する</button>
                <button type="button" onclick="location.href='/polls/{{ question.id }}'">詳細に戻る</button>
            </div>

        {% endif %}
    </form>
</div>
{% endblock %}

python_django/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="outer">
    <h1>{{ question.question_text }}</h1>
    
    <div class="inner">
        <table>
            {% for choice in question.choice_set.all %}
            <tr>
                <td>{{ choice.choice_text }}</td>
                <td>--</td> 
                <td>{{ choice.votes }}票</td>    
            </tr>
            {% endfor %}
        </table>
    <br>
    <button type="button" onclick="location.href='/polls/{{ question.id }}/'">もう一回投票する</button>
    <button type="button" onclick="location.href='/polls/'">一覧画面に戻る</button>
    </div>
</div>
{% endblock %}